Update shrink-backup
Trying to figure out best usage of parted vs sfdisk

diff --git a/shrink-backup b/shrink-backup
--- a/shrink-backup
+++ b/shrink-backup
@@ -14,7 +14,7 @@
 #    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 #    GNU General Public License for more details.
 #
-#    11/2023
+#    10/2023
 #    Marcus Johansson
 #    https://github.com/UnconnectedBedna/shrink-backup
 ##############################################################################
@@ -168,30 +168,20 @@ function debug() {
 function get_dev_variables() {
 
   # Check if separate boot and root partition exists and set variables accordingly
-  #LOCAL_DEV_MAJ=$(lsblk -lpo mountpoint,maj:min | grep '/ ' | awk '{print $2}' | cut -d : -f 1)
   LOCAL_DEV_PTUUID=$(lsblk -lpo mountpoint,ptuuid | grep '/ ' | awk '{print $2}')
   LOCAL_DEV_PATH=$(lsblk -lpo ptuuid,type,path | grep "$LOCAL_DEV_PTUUID" | grep 'disk' | awk '{print $3}')
-  #LOCAL_ROOT_PARTN=$(lsblk -lpo mountpoint,partn | grep '/ ' | awk '{print $2}') # PARTN can only be used on arch :(
-  #LOCAL_DEV_PATH=$(lsblk -lpo maj:min,type,path | grep "$LOCAL_DEV_MAJ" | grep 'disk' | awk '{print $3}')
   debug 'DEBUG' "LOCAL_DEV_PTUUID=$LOCAL_DEV_PTUUID | LOCAL_DEV_PATH=$LOCAL_DEV_PATH"
   if [ $(lsblk | grep -c 'boot') -ne 0 ]; then
     debug 'INFO' 'Separate boot partition detected'
-    #LOCAL_DEV_MIN=$(lsblk -lpo mountpoint,maj:min | grep '/boot' | awk '{print $2}' | cut -d : -f 2)
-    #LOCAL_DEV_MIN=$(( LOCAL_DEV_MIN - 1 ))
-    #LOCAL_DEV_PATH=$(lsblk -lpo maj:min,type,path | grep "${LOCAL_DEV_MAJ}:${LOCAL_DEV_MIN}" | grep 'disk' | awk '{print $3}')
     LOCAL_DEV_BOOT_PATH=$(lsblk -lpo mountpoint,path | grep 'boot' | awk '{print $2}')
     LOCAL_DEV_ROOT_PATH=$(lsblk -lpo mountpoint,path | grep '/ ' | awk '{print $2}')
     debug 'DEBUG' "LOCAL_DEV_ROOT_PATH=${LOCAL_DEV_ROOT_PATH} | LOCAL_DEV_BOOT_PATH=$LOCAL_DEV_BOOT_PATH"
   else
     debug 'INFO' 'No boot partition detected'
-    #LOCAL_DEV_MIN=$(lsblk -lpo mountpoint,maj:min | grep '/ ' | awk '{print $2}' | cut -d : -f 2)
-    #LOCAL_DEV_MIN=$(( LOCAL_DEV_MIN - 1 ))
-    #LOCAL_DEV_PATH=$(lsblk -lpo maj:min,type,path | grep "${LOCAL_DEV_MAJ}:${LOCAL_DEV_MIN}" | grep 'disk' | awk '{print $3}')
     LOCAL_DEV_ROOT_PATH=$(lsblk -lpo mountpoint,path | grep '/ ' | awk '{print $2}')
     debug 'DEBUG' "LOCAL_DEV_ROOT_PATH=$LOCAL_DEV_ROOT_PATH"
   fi
   LOCAL_ROOT_PARTN=$(parted -sm "$LOCAL_DEV_PATH" print | tail -1 | cut -d : -f 1)
-  #debug 'DEBUG' "LOCAL_DEV_PATH=${LOCAL_DEV_PATH} | LOCAL_DEV_MAJ=$LOCAL_DEV_MAJ | LOCAL_ROOT_PARTN=$LOCAL_ROOT_PARTN"
   debug 'DEBUG' "LOCAL_ROOT_PARTN=$LOCAL_ROOT_PARTN"
 
   # Collecting data and making calculations
@@ -209,10 +199,10 @@ function get_dev_variables() {
   LOCAL_RESIZE2FS_MIN=$(( LOCAL_RESIZE2FS_MIN * BLOCKSIZE )) # bytes
   debug 'DEBUG' "LOCAL_RESIZE2FS_MIN=${LOCAL_RESIZE2FS_MIN} Bytes"
   # Method 1, using the value of "size - available"
-  LOCAL_DF_OUTPUT=( $(df / --output=size,avail | tail -1) ) # 1k blocks, 0 is the first position in an array
+  LOCAL_DF_OUTPUT=( $(df / -k --sync --output=size,avail | tail -1) ) # 1k blocks, 0 is the first position in an array
   LOCAL_USED_SPACE=$(( (${LOCAL_DF_OUTPUT[0]} - ${LOCAL_DF_OUTPUT[1]}) * 1024 )) # bytes, df is in 1k blocks, 0 is the first position
   # Method 2, using "used space" straight up
-  #LOCAL_DF_OUTPUT=( $(df / --output=used | tail -1) ) # 1k blocks
+  #LOCAL_DF_OUTPUT=( $(df / -k --sync --output=used | tail -1) ) # 1k blocks
   #LOCAL_USED_SPACE=$(( LOCAL_DF_OUTPUT * 1024 )) # bytes, df is in 1k blocks
   ADDED_SPACE=$(( ADDED_SPACE * 1024 * 1024 )) # bytes
   WIGGLEROOM=134217728 # 128MB = 134217728B, 192MB = 201326592B
@@ -457,20 +447,20 @@ function do_resize() {
 
     echo '## Removing partition...'
     sleep 1
-    debug 'INFO' 'Using sfdisk to remove partition'
-    debug 'DEBUG' "Running: sfdisk --delete $LOOP $IMG_ROOT_PARTN"
-    #sfdisk --delete -f "$LOOP" "$IMG_ROOT_PARTN" # seems to fail if img size is very big
-    #debug 'DEBUG' "Running: parted -s $LOOP rm $IMG_ROOT_PARTN"
-    #parted -s "$LOOP" rm "$IMG_ROOT_PARTN" # does not work, still asking for user confirmation even though --script is used
-    #debug 'INFO' 'Using parted to remove root partition'
+    #debug 'INFO' 'Using sfdisk to remove root partition'
+    debug 'INFO' 'Using parted to remove root partition'
+    #debug 'DEBUG' "Running: sfdisk --delete -f $LOOP $IMG_ROOT_PARTN"
+    debug 'DEBUG' "Running: parted -s -f $LOOP rm $IMG_ROOT_PARTN"
     #debug 'DEBUG' "Running: printf 'Ignore\\\n'$IMG_ROOT_PARTN | parted $LOOP rm $IMG_ROOT_PARTN ---pretend-input-tty"
-    if ! output=$(sfdisk --delete -f "$LOOP" "$IMG_ROOT_PARTN" 2>&1); then
-    #if ! output=$(printf 'Ignore\n'$IMG_ROOT_PARTN | parted $LOOP rm $IMG_ROOT_PARTN ---pretend-input-tty 2>&1); then
-      echo -e "$output\n## SFDISK FAILED!!!"
-      #echo -e "$output\n## PARTED FAILED!!!"
+
+    #if ! output=$(sfdisk --delete -f "$LOOP" "$IMG_ROOT_PARTN" 2>&1); then # might fail if img size is very big
+    if ! output=$(parted -s -f "$LOOP" rm "$IMG_ROOT_PARTN" 2>&1); then # for some reason this line works here but not when creating img
+    #if ! output=$(printf 'Ignore\n'$IMG_ROOT_PARTN | parted $LOOP rm $IMG_ROOT_PARTN ---pretend-input-tty 2>&1); then # raspberry pi os does not like this method
+      #echo -e "$output\n## SFDISK FAILED!!!"
+      echo -e "$output\n## PARTED FAILED!!!"
       debug 'BREAK'
-      debug 'ERROR' "SFDISK FAILED:\n$output\n------------------------------------------------------------------------------"
-      #debug 'ERROR' "PARTED FAILED:\n$output\n------------------------------------------------------------------------------"
+      #debug 'ERROR' "SFDISK FAILED:\n$output\n------------------------------------------------------------------------------"
+      debug 'ERROR' "PARTED FAILED:\n$output\n------------------------------------------------------------------------------"
       exit 1
     fi
 
@@ -521,10 +511,10 @@ function do_resize() {
     echo '## Shrinking partition...'
     sleep 1
     debug 'INFO' 'Using parted to shrink partition'
-    #debug 'DEBUG' "Running: parted -s -a none $LOOP unit B resizepart $IMG_ROOT_PARTN $TRUNCATE_TOTAL"
+    #debug 'DEBUG' "Running: parted -s -f -a none $LOOP unit B resizepart $IMG_ROOT_PARTN $TRUNCATE_TOTAL"
     debug 'DEBUG' "Running: printf 'Yes\\\n' | parted -a none $LOOP unit B resizepart $IMG_ROOT_PARTN $TRUNCATE_TOTAL ---pretend-input-tty"
-    #parted -s -a none "$LOOP" unit B resizepart "$IMG_ROOT_PARTN" "$TOTAL"
-    #if ! output=$(parted -s -a none "$LOOP" unit B resizepart "$IMG_ROOT_PARTN" "$TRUNCATE_TOTAL" 2>&1); then # does not work, still asking for user confirmation even though --script is used
+
+    #if ! output=$(parted -s -f -a none "$LOOP" unit B resizepart "$IMG_ROOT_PARTN" "$TRUNCATE_TOTAL" 2>&1); then # does not work, still asking for user confirmation even though --script and -f (automatically answer "fix" to exceptions in script mode) is used
     if ! output=$(printf 'Yes\n' | parted -a none "$LOOP" unit B resizepart "$IMG_ROOT_PARTN" "$TRUNCATE_TOTAL" ---pretend-input-tty 2>&1); then
       echo -e "$output\n## PARTED FAILED!!!"
       debug 'BREAK'
@@ -621,7 +611,7 @@ function make_img() {
     echo "# Autoexpand filesystem at boot: $AUTOEXPAND"
     echo "# Use exclude.txt: $EXCLUDE_FILE"
     echo "# Bootsector size: $(( LOCAL_BOOTSECTOR / 1024 / 1024 ))MB"
-    echo "# Estemated root usage: $(( $(df / --output=used | tail -1) / 1024 ))MB"
+    echo "# Estemated root usage: $(( $(df / -k --sync --output=used | tail -1) / 1024 ))MB"
     if [ "$RESIZE2FS_RUN" == true ]; then
       echo "# Resize2fs decide minimum (root partition): $(( LOCAL_RESIZE2FS_MIN / 1024 / 1024 ))MB"
       echo "# Total img size: $(( TRUNCATE_TOTAL / 1024 / 1024 ))MB"
@@ -680,7 +670,7 @@ function make_img() {
     echo "# Autoexpand filesystem at boot: $AUTOEXPAND"
     echo "# Use exclude.txt: $EXCLUDE_FILE"
     echo "# Bootsector size: $(( LOCAL_BOOTSECTOR / 1024 / 1024 ))MB"
-    echo "# Estemated root usage: $(( $(df / --output=used | tail -1) / 1024 ))MB"
+    echo "# Estemated root usage: $(( $(df / -k --sync --output=used | tail -1) / 1024 ))MB"
     if [ "$RESIZE2FS_RUN" == true ]; then
       echo "# Resize2fs decide minimum (root partition): $(( LOCAL_RESIZE2FS_MIN / 1024 / 1024 ))MB"
       echo "# Total img size: $(( TRUNCATE_TOTAL / 1024 / 1024 ))MB"
@@ -747,12 +737,14 @@ function make_img() {
   echo '## Removing root partition...'
   sleep 1
   debug 'INFO' 'Using sfdisk to remove root partition'
-  debug 'DEBUG' "Running: sfdisk --delete -f $LOOP $LOCAL_ROOT_PARTN"
-  #parted -s "$LOOP" rm "$IMG_ROOT_PARTN" # does not work, still asking for user confirmation even though --script is used
   #debug 'INFO' 'Using parted to remove root partition'
+  debug 'DEBUG' "Running: sfdisk --delete -f $LOOP $LOCAL_ROOT_PARTN"
+  #debug 'DEBUG' "Running: parted -s -f $LOOP rm $LOCAL_ROOT_PARTN"
   #debug 'DEBUG' "Running: printf 'Ignore\\\n'$LOCAL_ROOT_PARTN | parted $LOOP rm $LOCAL_ROOT_PARTN ---pretend-input-tty"
-  if ! output=$(sfdisk --delete -f "$LOOP" "$LOCAL_ROOT_PARTN" 2>&1); then # seems to fail if img size is very big
-  #if ! output=$(printf 'Ignore\n'$LOCAL_ROOT_PARTN | parted $LOOP rm $LOCAL_ROOT_PARTN ---pretend-input-tty 2>&1); then # fails on raspberry pi os
+
+  if ! output=$(sfdisk --delete -f "$LOOP" "$LOCAL_ROOT_PARTN" 2>&1); then # might fail if img size is very big
+  #if ! output=$(parted -s -f "$LOOP" rm "$LOCAL_ROOT_PARTN" 2>&1); then # does not work, still asking for user confirmation even though --script and -f (automatically answer "fix" to exceptions in script mode) is used. faults with: "Error: Can't have a partition outside the disk!". for some reason this line works in the resizing function
+  #if ! output=$(printf 'Ignore\n'$LOCAL_ROOT_PARTN | parted $LOOP rm $LOCAL_ROOT_PARTN ---pretend-input-tty 2>&1); then # raspberry pi os does not like this method, keep for memory
     echo -e "$output\n## SFDISK FAILED!!!"
     #echo -e "$output\n## PARTED FAILED!!!"
     debug 'BREAK'
@@ -884,7 +876,7 @@ function do_backup() {
       echo "# New img size: $(( TRUNCATE_TOTAL / 1024 / 1024 ))MB"
       echo "# Difference: $(( ADDED_SPACE / 1024 / 1024 ))MB"
     else
-      echo "# Estemated root usage: $(( $(df / --output=used | tail -1) / 1024 ))MB"
+      echo "# Estemated root usage: $(( $(df / -k --sync --output=used | tail -1) / 1024 ))MB"
       echo "# Total img size: $(( IMG_SIZE / 1024 / 1024 ))MB"
     fi
     echo '##############################################################################'
@@ -924,7 +916,7 @@ function do_backup() {
       echo "# Difference: $(( ADDED_SPACE / 1024 / 1024 ))MB"
     else
 
-      echo "# Used space on root: $(( $(df / --output=used | tail -1) / 1024 ))MB"
+      echo "# Used space on root: $(( $(df / -k --sync --output=used | tail -1) / 1024 ))MB"
       echo "# Total img size: $(( IMG_SIZE / 1024 / 1024 ))MB"
     fi
     echo '# PRESS CTRL+C WITHIN 5s TO CANCEL!'
@@ -962,7 +954,6 @@ function do_backup() {
       return 0
 
     else
-      echo '## Difference too small, no resizing needed...'
       debug 'INFO' 'Img root partition is >=64MB smaller or <=512MB bigger compared size to resize2fs recommended minimum, not resizing'
       sleep 1
     fi
@@ -1081,7 +1072,7 @@ LOCAL_DEV_ROOT_PATH=\$(lsblk -lpo mountpoint,path | grep '/ ' | awk '{print \$2}
 LOCAL_ROOT_START=\$(fdisk -lo start "\$LOCAL_DEV_PATH" | tail -1 | awk '{print \$1}') # blocks, 512B block size
 LOCAL_ROOT_START=\$(( LOCAL_ROOT_START * 512 )) # bytes
 
-sfdisk --delete "\$LOCAL_DEV_PATH" "\$LOCAL_ROOT_PARTN"
+sfdisk --delete -f "\$LOCAL_DEV_PATH" "\$LOCAL_ROOT_PARTN"
 parted -s -a none "\$LOCAL_DEV_PATH" unit B mkpart primary ext4 "\$LOCAL_ROOT_START" 100%
 resize2fs -f "\$LOCAL_DEV_ROOT_PATH"
 sync
@@ -1137,7 +1128,7 @@ LOCAL_DEV_ROOT_PATH=\$(lsblk -lpo mountpoint,path | grep '/ ' | awk '{print \$2}
 LOCAL_ROOT_START=\$(fdisk -lo start "\$LOCAL_DEV_PATH" | tail -1 | awk '{print \$1}') # blocks, 512B block size
 LOCAL_ROOT_START=\$(( LOCAL_ROOT_START * 512 )) # bytes
 
-sfdisk --delete "\$LOCAL_DEV_PATH" "\$LOCAL_ROOT_PARTN"
+sfdisk --delete -f "\$LOCAL_DEV_PATH" "\$LOCAL_ROOT_PARTN"
 parted -s -a none "\$LOCAL_DEV_PATH" unit B mkpart primary ext4 "\$LOCAL_ROOT_START" 100%
 resize2fs -f "\$LOCAL_DEV_ROOT_PATH"
 sync
