Update shrink-backup
Implemented ability to set custom device that root resides on if not on mmcblk0

diff --git a/shrink-backup b/shrink-backup
--- a/shrink-backup
+++ b/shrink-backup
@@ -65,8 +65,9 @@ function cleanup() {
     echo '## Done.'
     echo "## Elapsed time: $(date -d@$SECONDS -u +%M.%S)"
     debug 'INFO' "Elapsed time: $(date -d@$SECONDS -u +%M.%S)"
-    debug 'DEBUG' "Exiting script\n##############################################################################"
+    debug 'DEBUG' 'Exiting script'
   fi
+  echo '##############################################################################' >> "$LOG_FILE"
 }
 trap cleanup EXIT SIGTERM
 trap "exit 3" SIGINT
@@ -86,6 +87,7 @@ EXCLUDE_FILE=false
 AUTOEXPAND=true
 RESIZE2FS_RUN=false
 UPDATE=false
+CUSTOM_DEV_PATH=false
 LOG_FILE="$(dirname "$0")/shrink-backup.log"
 
 # Function to display help information, debug is not configured/working
@@ -95,33 +97,39 @@ help() {
 Script for creating an .img file and subsequently keeing it updated (-B), autoexpansion is enabled by default
 Directory where .img file is created is automatically excluded in backup
 ########################################################################
-Usage: sudo $(basename "$0") [-Uatyedh] imagefile.img [extra space (MB)]
-  -U         Update the img file (rsync to existing backup .img), no resizing, -a is ignored
+Usage: sudo $(basename "$0") [-Uatyeldh] imagefile.img [extra space (MB)]
+  -U         Update the img file (rsync to existing backup .img), no resizing, -a and -d is disregarded
   -a         Let resize2fs decide minimum space (extra space is ignored), disabled if using -U
   -t         Use exclude.txt in same folder as script to set excluded directories
              One directory per line: "/dir" or "/dir/*" to only exclude contents
   -y         Disable prompts in script
   -e         DO NOT expand filesystem when image is booted
-  -d         Write debug messages in log file shrink-backup.log in same directory as script
+  -l         Write debug messages in log file shrink-backup.log in same directory as script
+  -d [PATH]  Use custom device path. EXPERIMENTAL, default = /dev/mmcblk0
+             MAXIMUM 2 partitions, more and the script will not function correctly!
+             Feedback on functionality is apreciated (https://github.com/UnconnectedBedna/shrink-backup/discussions)
   -h --help  Show this help snippet
 ########################################################################
 Example: sudo $(basename "$0") -at /path/to/backup.img
 Example: sudo $(basename "$0") -e -y /path/to/backup.img 1000
-Example: sudo $(basename "$0") -Ut /path/to/backup.img
+Example: sudo $(basename "$0") -Utl /path/to/backup.img
+Example: sudo $(basename "$0") -ad /dev/sda /path/to/backup.img
+Example: sudo $(basename "$0") -atd /dev/nvme0n1 /path/to/backup.img
 EOM
   echo "$help"
   exit 2
 }
 
 # Parse command-line options
-while getopts ":Uatyedh" opt; do
+while getopts ":Uatyeldh" opt; do
   case ${opt} in
     U) UPDATE=true;;
     a) RESIZE2FS_RUN=true;;
     t) EXCLUDE_FILE=true;;
     y) PROMPTS=false;;
     e) AUTOEXPAND=false;;
-    d) DEBUG=true;;
+    l) DEBUG=true;;
+    d) CUSTOM_DEV_PATH=true;;
     h) help;;
     *) help;;
   esac
@@ -148,12 +156,6 @@ function debug() {
   fi
 }
 
-
-debug 'INFO' "Debugging requested, writing to log file $(basename "$LOG_FILE")..."
-debug 'INFO' "Update existing img file, UPDATE=$UPDATE"
-debug 'INFO' "RESIZE2FS_RUN=$RESIZE2FS_RUN"
-debug 'INFO' "Prompt for user confirmation, PROMPTS=$PROMPTS"
-debug 'INFO' "Enable AUTOEXPAND=$AUTOEXPAND"
 
 
 # Function to create a backup img file
@@ -187,23 +189,47 @@ function make_img() {
     debug 'USER_INPUT' "User requested ${ADDED_SPACE}MB as ADDED_SPACE"
   fi
 
-  if [ -e /dev/mmcblk0p2 ]; then
-    MMCBLK='/dev/mmcblk0p2'
-    debug 'DEBUG' "2 partitions detected, setting MMCBLK=$MMCBLK"
+  # Set HD_DEV_PATH to default if custom is not defined
+  if [ -z "$HD_DEV_PATH" ]; then
+    HD_DEV_PATH='/dev/mmcblk0'
+  fi
+
+  # Check that not more than 2 partitions exist
+  if [ $(fdisk -lo device "$HD_DEV_PATH" | grep -c "$HD_DEV_PATH") -gt 3 ]; then
+    echo "More than 2 partitions detected on $HD_DEV_PATH"
+    echo "Operation not supported"
+    debug 'ERROR' 'More than 2 partitions not supported by script, exit 2'
+    exit 2
+  fi
+
+  # Check if custom device path is requested and set DEV_PATH accordingly
+  if [ "$CUSTOM_DEV_PATH" == false ]; then
+    if [ $(sudo fdisk -lo device "$HD_DEV_PATH" | grep -c "$HD_DEV_PATH") -gt 2 ]; then
+      DEV_PATH='/dev/mmcblk0p2'
+      debug 'DEBUG' "2 partitions detected, setting DEV_PATH=$DEV_PATH"
+    else
+      DEV_PATH='/dev/mmcblk0p1'
+      debug 'DEBUG' "1 partition detected, setting DEV_PATH=$DEV_PATH"
+    fi
   else
-    MMCBLK='/dev/mmcblk0p1'
-    debug 'DEBUG' "1 partition detected, setting MMCBLK=$MMCBLK"
+    if [ $(sudo fdisk -lo device "$HD_DEV_PATH" | grep -c "$HD_DEV_PATH") -gt 2 ]; then
+      DEV_PATH=$(sudo fdisk -lo device "$HD_DEV_PATH" | grep "$HD_DEV_PATH" | tail -1)
+      debug 'DEBUG' "2 partitions detected, setting DEV_PATH=$DEV_PATH"
+    else
+      DEV_PATH=$(sudo fdisk -lo device "$HD_DEV_PATH" | grep "$HD_DEV_PATH" | tail -1)
+      debug 'DEBUG' "1 partition detected, setting DEV_PATH=$DEV_PATH"
+    fi
   fi
 
   # BOOTSECTOR is actually the startsector on the root partition
-  BOOTSECTOR=( $(fdisk -lo start /dev/mmcblk0 | tail -1) ) # blocks, 512B block size
+  BOOTSECTOR=( $(fdisk -lo start "$HD_DEV_PATH" | tail -1) ) # blocks, 512B block size
   DDBOOTSECTOR=$(( BOOTSECTOR + 256 )) # blocks, 8192 + 256 = 8448 (adding 256 extra to be safe)
   debug 'DEBUG' 'Calculating size for dd to cover bootsector in blocks (512B block size) and adding 256 to overlap into root'
   debug 'INFO' "BOOTSECTOR=${BOOTSECTOR} blocks - this is actually the startsector for the root partition"
   debug 'INFO' "DDBOOTSECTOR=${DDBOOTSECTOR} blocks"
   BOOTSECTOR=$(( BOOTSECTOR * 512 )) # bytes, 8192 x 512 = 4194304
-  BLOCKSIZE=$(dumpe2fs -h "$MMCBLK" | grep "Block size" | awk '{print $3}') # bytes
-  RESIZE2FS_MIN=$(resize2fs -P "$MMCBLK" | awk '{print $7}' | tail -1) # blocks
+  BLOCKSIZE=$(dumpe2fs -h "$DEV_PATH" | grep "Block size" | awk '{print $3}') # bytes
+  RESIZE2FS_MIN=$(resize2fs -P "$DEV_PATH" | awk '{print $7}' | tail -1) # blocks
   RESIZE2FS_MIN=$(( RESIZE2FS_MIN * BLOCKSIZE )) # bytes
   #DF_OUTPUT=( $(df / --output=size,avail | tail -1) ) # 1k blocks, 0 is the first position in an array
   #USED_SPACE=$(( (${DF_OUTPUT[0]} - ${DF_OUTPUT[1]}) * 1024 )) # bytes, df is 1k block size, 0 is the first position
@@ -266,10 +292,10 @@ function make_img() {
     read -p "Do you want to continue? [y/n] " -n 1 -r
     debug 'INFO' 'Do you want to continue? [y/n]'
     if ! [[ "$REPLY" =~ ^[Yy]$ ]]; then
-      debug 'USER_INPUT' 'Aborted by user'
+      debug 'USER_INPUT' 'Aborted by user, exit 2'
       echo ''
       echo 'Aborting...'
-      exit 1
+      exit 2
     fi
     echo ''
     debug 'USER_INPUT' 'Y or y pressed to confirm'
@@ -282,10 +308,10 @@ function make_img() {
       read -p "Do you want to overwrite? [y/n] " -n 1 -r
       debug 'INFO' 'Do you want to overwrite? [y/n]'
       if ! [[ "$REPLY" =~ ^[Yy]$ ]]; then
-        debug 'USER_INPUT' 'Aborted by user'
+        debug 'USER_INPUT' 'Aborted by user, exit 2'
         echo ''
         echo 'Aborting...'
-        exit 1
+        exit 2
       fi
       echo ''
       debug 'USER_INPUT' 'Overwrite confirmed by user'
@@ -328,7 +354,7 @@ function make_img() {
   # Create and dd bootsector
   echo '## Creating bootsector...'
   debug 'INFO' "Using dd to create bootsector, bs=512 count=$DDBOOTSECTOR"
-  if ! output=$(dd bs=512 count=$DDBOOTSECTOR if=/dev/mmcblk0 of="$IMG_FILE" conv=noerror,sync status=progress 2>&1 | tee /dev/tty); then
+  if ! output=$(dd bs=512 count=$DDBOOTSECTOR if="$HD_DEV_PATH" of="$IMG_FILE" conv=noerror,sync status=progress 2>&1 | tee /dev/tty); then
     echo -e "$output\nDD TO BOOTSECTOR FAILED!!!"
     debug 'BREAK'
     debug 'ERROR' "DD TO BOOTSECTOR FAILED:\n$output\n------------------------------------------------------------------------------"
@@ -336,7 +362,7 @@ function make_img() {
   fi
   output=$(echo "$output" | tail -3 )
   debug 'BREAK'
-  debug 'DEBUG' "Running: dd bs=512 count=$DDBOOTSECTOR if=/dev/mmcblk0 of=$IMG_FILE conv=noerror,sync status=progress\n$output\n------------------------------------------------------------------------------"
+  debug 'DEBUG' "Running: dd bs=512 count=$DDBOOTSECTOR if=$HD_DEV_PATH of=$IMG_FILE conv=noerror,sync status=progress\n$output\n------------------------------------------------------------------------------"
   sleep 2
 
   # Truncate file to correct size
@@ -366,7 +392,7 @@ function make_img() {
   # Remove partition
   echo '## Removing root partition...'
   debug 'INFO' 'Using sfdisk to remove root partition'
-  if [ -e /dev/mmcblk0p2 ]; then
+  if [ -e "$DEV_PATH" ]; then
     LOOP0='/dev/loop0p2'
     LOOP1='/dev/loop0p1'
     debug 'DEBUG' "2 partitions detected, setting LOOP0=$LOOP0 and LOOP1=$LOOP1"
@@ -405,8 +431,8 @@ function make_img() {
   # Format filesystem
   echo '## Formatting filesystem...'
   debug 'INFO' 'Using mkfs.ext4 to format root filesystem'
-  LABEL=( $(lsblk -o label "$MMCBLK" | tail -1) )
-  UUID=( $(lsblk -o uuid "$MMCBLK" | tail -1) )
+  LABEL=( $(lsblk -o label "$DEV_PATH" | tail -1) )
+  UUID=( $(lsblk -o uuid "$DEV_PATH" | tail -1) )
   if ! output=$(mkfs.ext4 "$LOOP0" -U "$UUID" -L "$LABEL" -F -v 2>&1 | tee /dev/tty ); then
     echo -e "$output\nMKFS.EXT4 FAILED!!!"
     debug 'BREAK'
@@ -444,7 +470,7 @@ function make_img() {
   fi
   debug 'DEBUG' "Running: mount $LOOP0 $TMP_DIR"
   sleep 1
-  if [ -e /dev/mmcblk0p2 ]; then
+  if [ -e "$DEV_PATH" ]; then
     echo '## Mounting boot partition...'
     debug 'INFO' 'Separate boot partition detected, mounting boot inside img file'
     BOOT_PATH=$(cat /etc/fstab | grep '/boot' | awk '{print $2}')
@@ -535,7 +561,7 @@ function do_backup() {
   debug 'DEBUG' "Running: mount -o loop,offset=$OFFSET,x-mount.mkdir $IMG_FILE $TMP_DIR"
   sleep 1
 
-  if [ -e /dev/mmcblk0p2 ]; then
+  if [ -e "$DEV_PATH" ]; then
     echo '## Mounting boot...'
     debug 'INFO' 'Separate boot partition detected, mounting boot inside img file'
     OFFSET_BOOT=$(fdisk -lo start "$IMG_FILE" | tail -2 | head -1) # blocks, 512B block size
@@ -851,18 +877,36 @@ do
   if [[ "$1" =~ ^- ]]; then
     shift
   else
-    IMG_FILE="$1"
-    ADDED_SPACE="$2"
-    break
+    if [ $CUSTOM_DEV_PATH == true ]; then
+      HD_DEV_PATH="$1"
+      IMG_FILE="$2"
+      ADDED_SPACE="$3"
+      break
+    else
+      IMG_FILE="$1"
+      ADDED_SPACE="$2"
+      break
+    fi
   fi
 
 done
 
 # Check if the image file has the correct extension
 if [[ "$IMG_FILE" != *.img ]]; then
-  echo 'File must have .img extension'
+  echo 'ERROR! File must have .img extension'
   debug 'ERROR' 'File must have .img extension, exit 2'
   exit 2
+fi
+
+if [ "$DEBUG" == true ]; then
+  echo "Debugging selected, writing to $LOG_FILE"
+  debug 'INFO' "Debugging requested, writing to log file $(basename "$LOG_FILE")..."
+  debug 'INFO' "Update existing img file selected, UPDATE=$UPDATE"
+  debug 'INFO' "Requesting size from resize2fs selected, RESIZE2FS_RUN=$RESIZE2FS_RUN"
+  debug 'INFO' "Prompt for user confirmation, PROMPTS=$PROMPTS"
+  debug 'INFO' "Auto expansion enabled, AUTOEXPAND=$AUTOEXPAND"
+  debug 'INFO' "Custom device path selected, CUSTOM_DEV_PATH=$CUSTOM_DEV_PATH"
+  sleep 1
 fi
 
 if [ "$EXCLUDE_FILE" == true ]; then
